# syntax=docker /dockerfile:1
FROM alembic
FROM aniso8601
FROM attrs
FROM cffi
FROM click
FROM cloudpickle
FROM Flask
FROM Flask-Migrate
FROM flask-restx
FROM Flask-Script
FROM Flask-SQLAlchemy
FROM gevent
FROM greenlet
FROM gunicorn
FROM itsdangerous
FROM Jinja2
FROM jsonschema
FROM Mako
FROM MarkupSafe
FROM numpy
FROM pandas
FROM psycopg2-binary
FROM pycparser
FROM pyrsistent
FROM python-dateutil
FROM python-editor
FROM pytz
FROM scikit-learn
FROM scipy
FROM six
FROM SQLAlchemy
FROM unicode
FROM Unidecode
FROM Werkzeug
FROM xgboost
